### ISSUE TITLE
Update to linter API v2

### ISSUE THREAD

**Issue by Luthaf** [AtomLinter/linter-gfortran#7]
https://github.com/steelbrain/linter/blob/master/docs/guides/upgrading-to-standard-linter-v2.md

**Comment by Arcanemagus** [comment]
Note that as of v4.5.0 of `atom-package-deps` you can now specify a minimum version of a package, so with some configuration changes we can start safely upgrading providers to the v2 API 😁.

**Comment by Arcanemagus** [comment]
In the [v2.3.0 release](https://github.com/steelbrain/linter/releases/tag/v2.3.0) of `linter` support for the v1 API was removed, breaking semver. This means that this provider is no longer supported by the current version of `linter`.

To get this provider working again it will need to be upgrade to the v2 API, a guide for accomplishing that can be found here: [Upgrading to Standard Linter v2](https://github.com/steelbrain/linter/blob/v2.3.0/docs/guides/upgrading-to-standard-linter-v2.md).

Until this is fixed in order to use this provider you will need to downgrade to the last version of `linter` that supports the v1 API, you can do this with `apm install linter@2.2.0`.

**Comment by vzamanillo** [comment]
@Arcanemagus, In progress.
